doctrine:
    dbal:
        types:
            bigint: App\Doctrine\Type\IntegerBigintType
            phone_number: App\Doctrine\Type\PhoneNumberType
            jsonb: App\Doctrine\Type\JsonbType
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: 11
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                hydrators:
                    CursorPaginateHydrator: App\Doctrine\CursorPaginateHydrator
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    Gedmo:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                dql:
                    string_functions:
                        JSONB_EXISTS: App\Doctrine\DQL\JsonExistsFunction
