monolog:
    handlers:
        docker_debug_filter:
            type: filter
            handler: docker_debug
            min_level: info
            max_level: warning
        docker_debug:
            type: stream
            path: php://stdout
            channels: ["!request", "!php"]
        docker_error:
            level: error
            type: stream
            path: php://stderr
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: 'null'
            process_psr_3_messages: false
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        sentry:
            type: service
            id: Sentry\Monolog\Handler
            level: error
