fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
  prefix: /api

app.swagger_ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }