apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-prod
  name: postgres-prod-external
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-prod
    release: postgres-prod
    role: master
  type: LoadBalancer
